// Design tokens copied from the Google Stitch export (design/stitch/*.html, identical in all four
// screens): Material 3 colour roles, radii, spacing and the Inter type scale. The only change is
// the font stack: Inter is self-hosted through @fontsource-variable/inter ("Inter Variable").
import type { Config } from "tailwindcss";

const inter = ["Inter Variable", "Inter", "ui-sans-serif", "system-ui", "sans-serif"];

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#faf8ff",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#eef0ff",
        "primary-fixed": "#e2dfff",
        "surface-tint": "#4d44e3",
        "on-error": "#ffffff",
        outline: "#777587",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#ffd2be",
        "surface-dim": "#d2d9f4",
        "inverse-surface": "#283044",
        "on-primary-fixed": "#0f0069",
        error: "#ba1a1a",
        primary: "#3525cd",
        "on-secondary-fixed": "#07006c",
        tertiary: "#7e3000",
        "secondary-container": "#6063ee",
        "on-primary-fixed-variant": "#3323cc",
        secondary: "#4648d4",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#dae2fd",
        "tertiary-fixed": "#ffdbcc",
        "primary-container": "#4f46e5",
        "on-secondary-container": "#fffbff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#351000",
        "on-surface-variant": "#464555",
        "inverse-primary": "#c3c0ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "on-primary-container": "#dad7ff",
        "on-surface": "#131b2e",
        "on-secondary-fixed-variant": "#2f2ebe",
        background: "#faf8ff",
        "primary-fixed-dim": "#c3c0ff",
        "outline-variant": "#c7c4d8",
        "on-tertiary": "#ffffff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "secondary-fixed-dim": "#c0c1ff",
        "tertiary-container": "#a44100",
        "on-tertiary-fixed-variant": "#7b2f00",
        "secondary-fixed": "#e1e0ff",
        "surface-variant": "#dae2fd",
        "tertiary-fixed-dim": "#ffb695",
        "surface-bright": "#faf8ff",
        "on-background": "#131b2e",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1.25rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "space-lg": "1.25rem",
        margin: "1.5rem",
        "space-md": "0.75rem",
        "space-xl": "2rem",
      },
      fontFamily: {
        sans: inter,
        "label-md": inter,
        "headline-lg": inter,
        "headline-xl": inter,
        "headline-md": inter,
        "code-sm": inter,
        "body-md": inter,
        "label-sm": inter,
        "headline-sm": inter,
        "body-lg": inter,
        "body-sm": inter,
      },
      fontSize: {
        "label-md": ["13px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "code-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
